name: Build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [ main ]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"
      
      - name: Restore solution
        run: |
          dotnet restore
      
      - name: Setup NetcodeWeaver
        id: setup-netcode-weaver
        uses: Lordfirespeed/setup-netcode-weaver@main
        with:
          netcode-weaver-version: 2.4.0
          deps-packages: '[{"id": "UnityEngine.Modules", "version": "2022.3.9"}, {"id": "LethalCompany.GameLibs.Steam", "version": "45.0.2-alpha.1"}]'
          target-framework: "netstandard2.1"
      
      - name: See NetcodeWeaver location
        run: echo "${{ steps.setup-netcode-weaver.outputs.netcode-weaver-directory }}"
      
      - name: Install Thunderstore CLI
        run: |
          dotnet tool install -g tcli
      
      - name: Build solution
        run: |
          dotnet build -p:NETCODE_PATCHER_DIR="${{ steps.setup-netcode-weaver.outputs.netcode-weaver-directory }}"
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: "dist/*.zip"
